#!/usr/bin/env bash
# shellcheck disable=SC2153

FC_SYSCTL_KEYS='net.core.default_qdisc
net.ipv4.tcp_congestion_control
net.core.rmem_max
net.core.wmem_max
net.ipv4.tcp_rmem
net.ipv4.tcp_wmem
net.ipv4.tcp_moderate_rcvbuf
net.ipv4.tcp_window_scaling
net.ipv4.tcp_slow_start_after_idle
net.ipv4.tcp_mtu_probing
net.ipv4.tcp_fastopen
net.core.somaxconn
net.core.netdev_max_backlog'

FC_SYSCTL_TXN_WAS_MANAGED=0
FC_SYSCTL_TXN_BACKUP=''

fc_sysctl_path() {
  local root="${FLOWCRAFT_PROC_ROOT:-/proc/sys}"
  printf '%s/%s\n' "$root" "$(tr '.' '/' <<<"$1")"
}

fc_mem_mb() {
  awk '/^MemTotal:/ {printf "%d\n", $2 / 1024; found=1} END {if (!found) print 0}' \
    "${FLOWCRAFT_MEMINFO:-/proc/meminfo}" 2>/dev/null || printf '0\n'
}

fc_choose_cc() {
  local available
  available="$(cat "${FLOWCRAFT_CC_AVAILABLE:-/proc/sys/net/ipv4/tcp_available_congestion_control}" 2>/dev/null || true)"
  if [[ " $available " == *' bbr '* ]]; then
    printf 'bbr\n'
  elif [[ " $available " == *' cubic '* ]]; then
    printf 'cubic\n'
  else
    sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || printf 'cubic\n'
  fi
}

fc_buffer_cap() {
  local mem="$1" cap
  cap=$(( mem * 32768 ))
  (( cap < 4194304 )) && cap=4194304
  (( cap > 268435456 )) && cap=268435456
  printf '%s\n' "$cap"
}

fc_buffer_max() {
  local role="$1" rate="$2" rtt="$3" mem="$4" target cap
  cap="$(fc_buffer_cap "$mem")"
  if [[ "$role" == landing ]]; then
    if (( mem < 1024 )); then target=16777216; else target=33554432; fi
  else
    target=$(( rate * rtt * 125 * 2 + 2097152 ))
    (( target < 4194304 )) && target=4194304
  fi
  (( target > cap )) && target="$cap"
  printf '%s\n' "$target"
}

fc_sysctl_append() {
  local file="$1" key="$2" value="$3"
  if [[ -e "$(fc_sysctl_path "$key")" || ${FLOWCRAFT_ALLOW_MISSING_SYSCTL_TESTS:-0} == 1 ]]; then
    printf '%s = %s\n' "$key" "$value" >>"$file"
  else
    fc_warn "内核不支持 ${key}，已跳过。"
  fi
}

fc_sysctl_render() {
  local target="$1" mem rate max cc initial
  mem="$(fc_mem_mb)"
  (( mem > 0 )) || mem=1024
  rate="$PER_FLOW_MBPS"
  [[ "$ROLE" == landing && "$TOTAL_MBPS" -gt 0 ]] && rate="$TOTAL_MBPS"
  max="$(fc_buffer_max "$ROLE" "$rate" "$RTT_MS" "$mem")"
  cc="$(fc_choose_cc)"
  if [[ "$ROLE" == landing ]]; then initial=16384; else initial=262144; fi
  {
    printf '# Generated by FlowCraft %s; do not edit.\n' "$FLOWCRAFT_VERSION"
    printf '# role=%s rate=%sMbps rtt=%sms memory=%sMiB\n\n' "$ROLE" "$rate" "$RTT_MS" "$mem"
  } >"$target" || return 1
  fc_sysctl_append "$target" net.core.default_qdisc fq || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_congestion_control "$cc" || return 1
  fc_sysctl_append "$target" net.core.rmem_max "$max" || return 1
  fc_sysctl_append "$target" net.core.wmem_max "$max" || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_rmem "4096 131072 $max" || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_wmem "4096 $initial $max" || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_moderate_rcvbuf 1 || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_window_scaling 1 || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_slow_start_after_idle 0 || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_mtu_probing 1 || return 1
  fc_sysctl_append "$target" net.ipv4.tcp_fastopen 3 || return 1
  fc_sysctl_append "$target" net.core.somaxconn 4096 || return 1
  fc_sysctl_append "$target" net.core.netdev_max_backlog 16384
}

fc_sysctl_snapshot() {
  if [[ -e "$FC_SYSCTL_SNAPSHOT" || -L "$FC_SYSCTL_SNAPSHOT" ]]; then
    fc_sysctl_snapshot_validate
    return
  fi
  if [[ -e "$FC_SYSCTL_FILE" || -L "$FC_SYSCTL_FILE" ]]; then
    fc_warn 'FlowCraft sysctl 配置已存在但首次接管快照缺失。'
    return 1
  fi
  local key value temp checksum
  mkdir -p "$FC_STATE_DIR" || return 1
  temp="$(mktemp "$FC_STATE_DIR/.sysctl-snapshot.XXXXXX")" || return 1
  printf '# FlowCraft pre-apply snapshot v1\n' >"$temp" || { rm -f "$temp"; return 1; }
  while IFS= read -r key; do
    [[ -n "$key" && -e "$(fc_sysctl_path "$key")" ]] || continue
    if ! value="$(sysctl -n "$key" 2>/dev/null)" || [[ -z "$value" ]]; then
      fc_warn "无法读取受管理 sysctl 键的接管前值：$key"
      rm -f "$temp"
      return 1
    fi
    printf '%s=%s\n' "$key" "$value" >>"$temp" || { rm -f "$temp"; return 1; }
  done <<<"$FC_SYSCTL_KEYS"
  checksum="$(fc_sysctl_snapshot_checksum "$temp")" || { rm -f "$temp"; return 1; }
  printf '# CKSUM=%s\n' "$checksum" >>"$temp" || { rm -f "$temp"; return 1; }
  fc_atomic_replace "$temp" "$FC_SYSCTL_SNAPSHOT" 0600 || { rm -f "$temp"; return 1; }
  fc_sysctl_snapshot_validate
}

fc_sysctl_snapshot_checksum() {
  local crc bytes
  read -r crc bytes _ < <(cksum <"$1")
  printf '%s:%s\n' "$crc" "$bytes"
}

fc_sysctl_snapshot_validate() {
  local key value entries=0 seen='|' footer expected actual
  [[ -f "$FC_SYSCTL_SNAPSHOT" && -r "$FC_SYSCTL_SNAPSHOT" ]] || {
    fc_warn 'sysctl 快照不可读或不是普通文件。'
    return 1
  }
  [[ "$(head -n 1 "$FC_SYSCTL_SNAPSHOT")" == '# FlowCraft pre-apply snapshot v1' ]] || {
    fc_warn 'sysctl 快照头无效。'
    return 1
  }
  footer="$(tail -n 1 "$FC_SYSCTL_SNAPSHOT")"
  [[ "$footer" =~ ^#[[:space:]]CKSUM=([0-9]+):([0-9]+)$ ]] || {
    fc_warn 'sysctl 快照缺少完整性校验。'
    return 1
  }
  expected="${BASH_REMATCH[1]}:${BASH_REMATCH[2]}"
  actual="$(sed '$d' "$FC_SYSCTL_SNAPSHOT" | fc_sysctl_snapshot_checksum /dev/stdin)"
  [[ "$actual" == "$expected" ]] || {
    fc_warn 'sysctl 快照完整性校验失败。'
    return 1
  }
  while IFS='=' read -r key value || [[ -n "$key$value" ]]; do
    [[ -n "$key" ]] || { fc_warn 'sysctl 快照包含空键。'; return 1; }
    grep -Fxq "$key" <<<"$FC_SYSCTL_KEYS" || {
      fc_warn "sysctl 快照包含未知键：$key"
      return 1
    }
    [[ -n "$value" && "$seen" != *"|$key|"* ]] || {
      fc_warn "sysctl 快照包含空值或重复键：$key"
      return 1
    }
    seen+="$key|"
    entries=$((entries + 1))
  done < <(sed '1d;$d' "$FC_SYSCTL_SNAPSHOT")
  (( entries > 0 )) || { fc_warn 'sysctl 快照没有可恢复项。'; return 1; }
  while IFS= read -r key; do
    [[ -n "$key" && -e "$(fc_sysctl_path "$key")" ]] || continue
    awk -F= -v wanted="$key" '$1 == wanted {found=1} END {exit !found}' \
      "$FC_SYSCTL_SNAPSHOT" || {
      fc_warn "sysctl 快照未覆盖当前受支持键：$key"
      return 1
    }
  done <<<"$FC_SYSCTL_KEYS"
}

fc_sysctl_apply() {
  local temp
  mkdir -p "$(dirname "$FC_SYSCTL_FILE")" || return 1
  temp="$(mktemp "$(dirname "$FC_SYSCTL_FILE")/.flowcraft-sysctl.XXXXXX")" || return 1
  if ! fc_sysctl_render "$temp" || ! fc_atomic_replace "$temp" "$FC_SYSCTL_FILE" 0644; then
    rm -f "$temp"
    return 1
  fi
  (( FC_DRY_RUN == 1 )) && return 0
  sysctl -p "$FC_SYSCTL_FILE" >/dev/null
}

fc_sysctl_transaction_begin() {
  FC_SYSCTL_TXN_WAS_MANAGED=0
  FC_SYSCTL_TXN_BACKUP=''
  if [[ -e "$FC_SYSCTL_FILE" || -L "$FC_SYSCTL_FILE" ]]; then
    [[ -f "$FC_SYSCTL_FILE" && -r "$FC_SYSCTL_FILE" ]] || {
      fc_warn 'FlowCraft sysctl 配置不可读或不是普通文件。'
      return 1
    }
    fc_sysctl_snapshot_validate || {
      fc_warn 'FlowCraft sysctl 配置存在，但首次接管快照无效。'
      return 1
    }
    fc_sysctl_verify || return 1
    mkdir -p "$FC_STATE_DIR" || return 1
    FC_SYSCTL_TXN_BACKUP="$(mktemp "$FC_STATE_DIR/.sysctl-transaction.XXXXXX")" || return 1
    if ! cp "$FC_SYSCTL_FILE" "$FC_SYSCTL_TXN_BACKUP" ||
      ! cmp -s "$FC_SYSCTL_FILE" "$FC_SYSCTL_TXN_BACKUP" ||
      ! chmod 0600 "$FC_SYSCTL_TXN_BACKUP"; then
      rm -f "$FC_SYSCTL_TXN_BACKUP"
      FC_SYSCTL_TXN_BACKUP=''
      return 1
    fi
    FC_SYSCTL_TXN_WAS_MANAGED=1
  fi
}

fc_sysctl_transaction_restore() {
  local failed=0 temp
  if (( FC_SYSCTL_TXN_WAS_MANAGED == 1 )); then
    [[ -f "$FC_SYSCTL_TXN_BACKUP" && -r "$FC_SYSCTL_TXN_BACKUP" ]] || {
      fc_warn '本次 sysctl 事务备份缺失。'
      return 1
    }
    mkdir -p "$(dirname "$FC_SYSCTL_FILE")" || return 1
    temp="$(mktemp "$(dirname "$FC_SYSCTL_FILE")/.flowcraft-sysctl-restore.XXXXXX")" || return 1
    if ! cp "$FC_SYSCTL_TXN_BACKUP" "$temp" ||
      ! cmp -s "$FC_SYSCTL_TXN_BACKUP" "$temp" ||
      ! fc_atomic_replace "$temp" "$FC_SYSCTL_FILE" 0644; then
      rm -f "$temp"
      return 1
    fi
    sysctl -p "$FC_SYSCTL_FILE" >/dev/null 2>&1 || failed=1
    fc_sysctl_verify || failed=1
  else
    if ! rm -f "$FC_SYSCTL_FILE"; then
      fc_warn '无法删除本次应用生成的 sysctl 配置。'
      return 1
    fi
    if fc_has sysctl; then sysctl --system >/dev/null 2>&1 || failed=1; fi
    fc_sysctl_restore || failed=1
    if (( failed == 0 )) && ! rm -f "$FC_SYSCTL_SNAPSHOT"; then
      failed=1
    fi
  fi
  (( failed == 0 ))
}

fc_sysctl_transaction_cleanup() {
  [[ -z "$FC_SYSCTL_TXN_BACKUP" ]] || rm -f "$FC_SYSCTL_TXN_BACKUP"
  FC_SYSCTL_TXN_BACKUP=''
  FC_SYSCTL_TXN_WAS_MANAGED=0
}

fc_sysctl_verify() {
  local key expected actual failures=0 entries=0 seen='|'
  [[ -f "$FC_SYSCTL_FILE" && -r "$FC_SYSCTL_FILE" ]] || return 1
  while IFS='=' read -r key expected || [[ -n "$key$expected" ]]; do
    key="$(fc_normalize_ws "$key")"
    expected="$(fc_normalize_ws "$expected")"
    [[ -n "$key" && "$key" != \#* ]] || continue
    if ! grep -Fxq "$key" <<<"$FC_SYSCTL_KEYS" || [[ -z "$expected" || "$seen" == *"|$key|"* ]]; then
      fc_warn "FlowCraft sysctl 配置包含未知键、空值或重复键：$key"
      failures=$((failures + 1))
      continue
    fi
    seen+="$key|"
    entries=$((entries + 1))
    actual="$(fc_normalize_ws "$(sysctl -n "$key" 2>/dev/null || true)")"
    [[ "$actual" == "$expected" ]] || { fc_warn "sysctl 漂移：$key 期望 '$expected'，实际 '$actual'"; failures=$((failures + 1)); }
  done <"$FC_SYSCTL_FILE"
  (( entries > 0 && failures == 0 ))
}

fc_sysctl_restore() {
  local key value failures=0
  [[ -r "$FC_SYSCTL_SNAPSHOT" ]] || { fc_warn '没有 sysctl 快照。'; return 0; }
  fc_sysctl_snapshot_validate || return 1
  while IFS='=' read -r key value || [[ -n "$key$value" ]]; do
    [[ -n "$key" && "$key" != \#* && -n "$value" ]] || continue
    if ! sysctl -qw "$key=$value" >/dev/null 2>&1; then
      fc_warn "无法恢复 $key"
      failures=$((failures + 1))
    fi
  done <"$FC_SYSCTL_SNAPSHOT"
  (( failures == 0 ))
}
